/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.compiler.go.myGo.Expression3;
import org.xtext.compiler.go.myGo.MyGoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression3</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class Expression3Impl extends ExpressionImpl implements Expression3
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Expression3Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyGoPackage.Literals.EXPRESSION3;
  }

} //Expression3Impl
