/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.compiler.go.myGo.MyGoPackage;
import org.xtext.compiler.go.myGo.Receiver;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Receiver</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.compiler.go.myGo.impl.ReceiverImpl#getIdName <em>Id Name</em>}</li>
 *   <li>{@link org.xtext.compiler.go.myGo.impl.ReceiverImpl#getIdType <em>Id Type</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class ReceiverImpl extends MinimalEObjectImpl.Container implements Receiver
{
  /**
   * The default value of the '{@link #getIdName() <em>Id Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdName()
   * @generated
   * @ordered
   */
  protected static final String ID_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdName() <em>Id Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdName()
   * @generated
   * @ordered
   */
  protected String idName = ID_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getIdType() <em>Id Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdType()
   * @generated
   * @ordered
   */
  protected static final String ID_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdType() <em>Id Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdType()
   * @generated
   * @ordered
   */
  protected String idType = ID_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReceiverImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyGoPackage.Literals.RECEIVER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdName()
  {
    return idName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdName(String newIdName)
  {
    String oldIdName = idName;
    idName = newIdName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyGoPackage.RECEIVER__ID_NAME, oldIdName, idName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdType()
  {
    return idType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdType(String newIdType)
  {
    String oldIdType = idType;
    idType = newIdType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyGoPackage.RECEIVER__ID_TYPE, oldIdType, idType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyGoPackage.RECEIVER__ID_NAME:
        return getIdName();
      case MyGoPackage.RECEIVER__ID_TYPE:
        return getIdType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyGoPackage.RECEIVER__ID_NAME:
        setIdName((String)newValue);
        return;
      case MyGoPackage.RECEIVER__ID_TYPE:
        setIdType((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyGoPackage.RECEIVER__ID_NAME:
        setIdName(ID_NAME_EDEFAULT);
        return;
      case MyGoPackage.RECEIVER__ID_TYPE:
        setIdType(ID_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyGoPackage.RECEIVER__ID_NAME:
        return ID_NAME_EDEFAULT == null ? idName != null : !ID_NAME_EDEFAULT.equals(idName);
      case MyGoPackage.RECEIVER__ID_TYPE:
        return ID_TYPE_EDEFAULT == null ? idType != null : !ID_TYPE_EDEFAULT.equals(idType);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (idName: ");
    result.append(idName);
    result.append(", idType: ");
    result.append(idType);
    result.append(')');
    return result.toString();
  }

} //ReceiverImpl
