/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go;

import org.xtext.compiler.go.MyGoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyGoStandaloneSetup extends MyGoStandaloneSetupGenerated {
  public static void doSetup() {
    new MyGoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
