/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.ide;

import org.xtext.compiler.go.ide.AbstractMyGoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyGoIdeModule extends AbstractMyGoIdeModule {
}
