/*
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyGoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/compiler/go/parser/antlr/internal/InternalMyGo.tokens");
	}
}
