/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.compiler.go.myGo.Body#getLineCommand <em>Line Command</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.compiler.go.myGo.MyGoPackage#getBody()
 * @model
 * @generated
 */
public interface Body extends EObject
{
  /**
   * Returns the value of the '<em><b>Line Command</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.compiler.go.myGo.LineCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Line Command</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Command</em>' containment reference list.
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getBody_LineCommand()
   * @model containment="true"
   * @generated
   */
  EList<LineCommand> getLineCommand();

} // Body
