/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.compiler.go.myGo.Declarations#getFunctionDeclaration <em>Function Declaration</em>}</li>
 *   <li>{@link org.xtext.compiler.go.myGo.Declarations#getTypeDeclaration <em>Type Declaration</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.compiler.go.myGo.MyGoPackage#getDeclarations()
 * @model
 * @generated
 */
public interface Declarations extends EObject
{
  /**
   * Returns the value of the '<em><b>Function Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Declaration</em>' containment reference.
   * @see #setFunctionDeclaration(FunctionDeclaration)
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getDeclarations_FunctionDeclaration()
   * @model containment="true"
   * @generated
   */
  FunctionDeclaration getFunctionDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.compiler.go.myGo.Declarations#getFunctionDeclaration <em>Function Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Declaration</em>' containment reference.
   * @see #getFunctionDeclaration()
   * @generated
   */
  void setFunctionDeclaration(FunctionDeclaration value);

  /**
   * Returns the value of the '<em><b>Type Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Declaration</em>' containment reference.
   * @see #setTypeDeclaration(TypeDeclaration)
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getDeclarations_TypeDeclaration()
   * @model containment="true"
   * @generated
   */
  TypeDeclaration getTypeDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.compiler.go.myGo.Declarations#getTypeDeclaration <em>Type Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Declaration</em>' containment reference.
   * @see #getTypeDeclaration()
   * @generated
   */
  void setTypeDeclaration(TypeDeclaration value);

} // Declarations
