/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.compiler.go.myGo.MyGoPackage#getExpression2()
 * @model
 * @generated
 */
public interface Expression2 extends Expression
{
} // Expression2
