/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.myGo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.compiler.go.myGo.FuncCall#getReceiverInstance <em>Receiver Instance</em>}</li>
 *   <li>{@link org.xtext.compiler.go.myGo.FuncCall#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.compiler.go.myGo.FuncCall#getParametersValues <em>Parameters Values</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.compiler.go.myGo.MyGoPackage#getFuncCall()
 * @model
 * @generated
 */
public interface FuncCall extends LineCommand, Expression
{
  /**
   * Returns the value of the '<em><b>Receiver Instance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Receiver Instance</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver Instance</em>' containment reference.
   * @see #setReceiverInstance(ReceiverInstance)
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getFuncCall_ReceiverInstance()
   * @model containment="true"
   * @generated
   */
  ReceiverInstance getReceiverInstance();

  /**
   * Sets the value of the '{@link org.xtext.compiler.go.myGo.FuncCall#getReceiverInstance <em>Receiver Instance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver Instance</em>' containment reference.
   * @see #getReceiverInstance()
   * @generated
   */
  void setReceiverInstance(ReceiverInstance value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getFuncCall_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.compiler.go.myGo.FuncCall#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Parameters Values</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters Values</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters Values</em>' containment reference.
   * @see #setParametersValues(ParametersValues)
   * @see org.xtext.compiler.go.myGo.MyGoPackage#getFuncCall_ParametersValues()
   * @model containment="true"
   * @generated
   */
  ParametersValues getParametersValues();

  /**
   * Sets the value of the '{@link org.xtext.compiler.go.myGo.FuncCall#getParametersValues <em>Parameters Values</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters Values</em>' containment reference.
   * @see #getParametersValues()
   * @generated
   */
  void setParametersValues(ParametersValues value);

} // FuncCall
