/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.compiler.go.ui.AbstractMyGoUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyGoUiModule extends AbstractMyGoUiModule {
  public MyGoUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
