/**
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.ui.contentassist;

import org.xtext.compiler.go.ui.contentassist.AbstractMyGoProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyGoProposalProvider extends AbstractMyGoProposalProvider {
}
