/*
 * generated by Xtext 2.14.0
 */
package org.xtext.compiler.go.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyGoScopeProvider extends DelegatingScopeProvider {
}
